export interface Country {
  code: string;  // ISO 3166-1 alpha-2
  name: string;
  currency: string;  // ISO 4217
}

export const COUNTRIES: Country[] = [
  { code: "AE", name: "United Arab Emirates", currency: "AED" },
  { code: "AR", name: "Argentina", currency: "ARS" },
  { code: "AT", name: "Austria", currency: "EUR" },
  { code: "AU", name: "Australia", currency: "AUD" },
  { code: "BD", name: "Bangladesh", currency: "BDT" },
  { code: "BE", name: "Belgium", currency: "EUR" },
  { code: "BM", name: "Bermuda", currency: "BMD" },
  { code: "BR", name: "Brazil", currency: "BRL" },
  { code: "BS", name: "Bahamas", currency: "BSD" },
  { code: "CA", name: "Canada", currency: "CAD" },
  { code: "CH", name: "Switzerland", currency: "CHF" },
  { code: "CL", name: "Chile", currency: "CLP" },
  { code: "CN", name: "China", currency: "CNY" },
  { code: "CO", name: "Colombia", currency: "COP" },
  { code: "CR", name: "Costa Rica", currency: "CRC" },
  { code: "CZ", name: "Czech Republic", currency: "CZK" },
  { code: "DE", name: "Germany", currency: "EUR" },
  { code: "DK", name: "Denmark", currency: "DKK" },
  { code: "DO", name: "Dominican Republic", currency: "DOP" },
  { code: "EG", name: "Egypt", currency: "EGP" },
  { code: "ES", name: "Spain", currency: "EUR" },
  { code: "FI", name: "Finland", currency: "EUR" },
  { code: "FR", name: "France", currency: "EUR" },
  { code: "GB", name: "United Kingdom", currency: "GBP" },
  { code: "GR", name: "Greece", currency: "EUR" },
  { code: "HK", name: "Hong Kong", currency: "HKD" },
  { code: "HU", name: "Hungary", currency: "HUF" },
  { code: "ID", name: "Indonesia", currency: "IDR" },
  { code: "IE", name: "Ireland", currency: "EUR" },
  { code: "IL", name: "Israel", currency: "ILS" },
  { code: "IN", name: "India", currency: "INR" },
  { code: "IT", name: "Italy", currency: "EUR" },
  { code: "JP", name: "Japan", currency: "JPY" },
  { code: "KE", name: "Kenya", currency: "KES" },
  { code: "KR", name: "South Korea", currency: "KRW" },
  { code: "KY", name: "Cayman Islands", currency: "KYD" },
  { code: "LU", name: "Luxembourg", currency: "EUR" },
  { code: "MA", name: "Morocco", currency: "MAD" },
  { code: "MX", name: "Mexico", currency: "MXN" },
  { code: "MY", name: "Malaysia", currency: "MYR" },
  { code: "NG", name: "Nigeria", currency: "NGN" },
  { code: "NL", name: "Netherlands", currency: "EUR" },
  { code: "NO", name: "Norway", currency: "NOK" },
  { code: "NZ", name: "New Zealand", currency: "NZD" },
  { code: "PA", name: "Panama", currency: "PAB" },
  { code: "PE", name: "Peru", currency: "PEN" },
  { code: "PH", name: "Philippines", currency: "PHP" },
  { code: "PK", name: "Pakistan", currency: "PKR" },
  { code: "PL", name: "Poland", currency: "PLN" },
  { code: "PT", name: "Portugal", currency: "EUR" },
  { code: "RO", name: "Romania", currency: "RON" },
  { code: "RU", name: "Russia", currency: "RUB" },
  { code: "SE", name: "Sweden", currency: "SEK" },
  { code: "SG", name: "Singapore", currency: "SGD" },
  { code: "TH", name: "Thailand", currency: "THB" },
  { code: "TR", name: "Turkey", currency: "TRY" },
  { code: "TW", name: "Taiwan", currency: "TWD" },
  { code: "UA", name: "Ukraine", currency: "UAH" },
  { code: "VN", name: "Vietnam", currency: "VND" },
  { code: "ZA", name: "South Africa", currency: "ZAR" },
];

// Unique currencies derived from countries list
export const CURRENCIES = Array.from(new Set(COUNTRIES.map(c => c.currency))).sort();
