export interface CountryData {
  slug: string;
  name: string;
  currency: string;
  currencyCode: string;
  commonBanks: string[];
  pensionImplications: string;
  expatPopulation: string;
  keyConsiderations: string[];
  overview: string;
  accountTypes: string[];
}

export const COUNTRIES: CountryData[] = [
  {
    slug: 'canada',
    name: 'Canada',
    currency: 'Canadian Dollar',
    currencyCode: 'CAD',
    commonBanks: ['RBC Royal Bank', 'TD Canada Trust', 'BMO', 'Scotiabank', 'CIBC'],
    pensionImplications: 'Canadian RRSPs and TFSAs are reportable on FBAR. RRSPs are also reportable under FATCA (Form 8938). TFSA income is generally taxable to US persons under IRC §7701(a)(30). The US-Canada tax treaty (Article XVIII) provides limited relief for RRSP contributions.',
    expatPopulation: 'Approximately 1 million US citizens live in Canada',
    keyConsiderations: [
      'RRSPs and TFSAs must be reported even if no distributions were taken',
      'Canadian mutual funds may be classified as PFICs (Passive Foreign Investment Companies)',
      'The US-Canada tax treaty affects treatment of Canadian pension income',
      'Joint accounts with Canadian spouse require FBAR reporting if aggregate exceeds $10,000',
    ],
    overview: 'Canada is home to the largest US expat population worldwide. US citizens and green card holders living in Canada must file FBARs for Canadian bank accounts, investment accounts, RRSPs, TFSAs, and RESPs if the aggregate value exceeds $10,000 at any point during the year.',
    accountTypes: ['Chequing and savings accounts', 'RRSPs (Registered Retirement Savings Plans)', 'TFSAs (Tax-Free Savings Accounts)', 'RESPs (Registered Education Savings Plans)', 'Non-registered investment accounts', 'GICs (Guaranteed Investment Certificates)'],
  },
  {
    slug: 'uk',
    name: 'United Kingdom',
    currency: 'British Pound',
    currencyCode: 'GBP',
    commonBanks: ['HSBC', 'Barclays', 'Lloyds', 'NatWest', 'Santander UK'],
    pensionImplications: 'UK workplace pensions and SIPPs (Self-Invested Personal Pensions) are reportable on FBAR. ISAs (Individual Savings Accounts) are reportable and their tax-free status is not recognized by the US. The US-UK tax treaty (Article 18) provides some pension relief.',
    expatPopulation: 'Approximately 300,000 US citizens live in the UK',
    keyConsiderations: [
      'ISAs are taxable to US persons despite UK tax-free status',
      'UK pensions (workplace and SIPPs) must be reported on FBAR',
      'Premium Bonds are reportable foreign financial accounts',
      'UK investment funds may be PFICs requiring Form 8621',
    ],
    overview: 'The United Kingdom is one of the top destinations for US expats in Europe. UK bank accounts, ISAs, SIPPs, workplace pensions, and investment accounts are all reportable on FinCEN Form 114 if the aggregate value of all foreign accounts exceeds $10,000.',
    accountTypes: ['Current and savings accounts', 'ISAs (Individual Savings Accounts)', 'SIPPs (Self-Invested Personal Pensions)', 'Workplace pensions', 'Premium Bonds', 'Stocks and shares ISAs'],
  },
  {
    slug: 'germany',
    name: 'Germany',
    currency: 'Euro',
    currencyCode: 'EUR',
    commonBanks: ['Deutsche Bank', 'Commerzbank', 'Sparkasse', 'DKB', 'ING Germany'],
    pensionImplications: 'German Riester-Rente and Rürup-Rente pension plans are reportable on FBAR. Betriebliche Altersvorsorge (company pensions) may also be reportable depending on the specific structure. The US-Germany tax treaty (Article 18A) provides limited pension relief.',
    expatPopulation: 'Approximately 200,000 US citizens live in Germany',
    keyConsiderations: [
      'Bausparkonto (building savings accounts) are reportable foreign accounts',
      'German Lebensversicherung (life insurance with investment component) may be reportable',
      'Riester and Rürup pension contributions are not tax-deductible on US returns',
      'German investment funds (Investmentfonds) may qualify as PFICs',
    ],
    overview: 'Germany hosts a significant US military and civilian expat population. German bank accounts at Sparkassen, Volksbanken, and commercial banks are reportable on FBAR. Pension plans, Bausparkonten, and investment accounts must also be reported if aggregate foreign account values exceed $10,000.',
    accountTypes: ['Girokonto (current accounts)', 'Sparkonto (savings accounts)', 'Tagesgeldkonto (overnight deposit accounts)', 'Festgeldkonto (fixed-term deposits)', 'Bausparkonten (building savings)', 'Depot accounts (securities)'],
  },
  {
    slug: 'mexico',
    name: 'Mexico',
    currency: 'Mexican Peso',
    currencyCode: 'MXN',
    commonBanks: ['BBVA Mexico', 'Banorte', 'Santander Mexico', 'Citibanamex', 'HSBC Mexico'],
    pensionImplications: 'Mexican AFORE retirement accounts (Administradoras de Fondos para el Retiro) are reportable on FBAR. The US-Mexico tax treaty provides limited relief for certain pension distributions.',
    expatPopulation: 'Approximately 1.6 million US citizens live in Mexico (largest expat population)',
    keyConsiderations: [
      'AFORE retirement accounts are reportable foreign financial accounts',
      'Mexican fideicomiso (bank trust for property) may create FBAR reporting obligations',
      'Currency conversion requires Treasury rates for MXN/USD at account maximum value',
      'Many US retirees in Mexico have both US and Mexican bank accounts',
    ],
    overview: 'Mexico has the largest US expat population of any country. US citizens and permanent residents living in Mexico must report Mexican bank accounts, AFORE retirement accounts, and investment accounts on FinCEN Form 114. The high MXN/USD exchange rate means even modest peso balances can trigger the $10,000 threshold.',
    accountTypes: ['Cuenta de cheques (checking accounts)', 'Cuenta de ahorro (savings accounts)', 'AFORE retirement accounts', 'CETES (government securities)', 'Pagarés (promissory notes)', 'Investment fund accounts'],
  },
  {
    slug: 'australia',
    name: 'Australia',
    currency: 'Australian Dollar',
    currencyCode: 'AUD',
    commonBanks: ['Commonwealth Bank', 'ANZ', 'Westpac', 'NAB', 'Macquarie Bank'],
    pensionImplications: 'Australian superannuation accounts are reportable on FBAR. Super funds are considered foreign financial accounts regardless of whether distributions have been taken. The US-Australia tax treaty does not provide comprehensive relief for superannuation taxation.',
    expatPopulation: 'Approximately 100,000-200,000 US citizens live in Australia',
    keyConsiderations: [
      'Superannuation accounts are reportable even before retirement age',
      'Australian managed funds may be classified as PFICs',
      'The US does not recognize tax-free status of Australian super contributions',
      'Employer super guarantee contributions create US tax obligations',
    ],
    overview: 'Australia is a popular destination for US expats in the Asia-Pacific region. Australian bank accounts, superannuation funds, term deposits, and investment accounts are all reportable on FBAR. Superannuation accounts are particularly important — they are reportable foreign financial accounts even though Australians cannot access them until preservation age.',
    accountTypes: ['Transaction and savings accounts', 'Superannuation funds', 'Term deposits', 'Managed investment accounts', 'Self-managed super funds (SMSFs)', 'Offset accounts (linked to mortgages)'],
  },
  {
    slug: 'japan',
    name: 'Japan',
    currency: 'Japanese Yen',
    currencyCode: 'JPY',
    commonBanks: ['MUFG Bank', 'Sumitomo Mitsui', 'Mizuho Bank', 'Japan Post Bank', 'Shinsei Bank'],
    pensionImplications: 'Japanese iDeCo (individual defined contribution) and corporate DC pension accounts are reportable on FBAR because they are held at private financial institutions. Government pensions — Kosei Nenkin (Employees Pension Insurance) and Kokumin Nenkin (National Pension) — are a gray area since they are administered by a government agency, not a private institution. The IRS has not issued definitive guidance on their reportability. The US-Japan tax treaty (Article 17) provides limited relief for pension distributions but does not affect FBAR obligations.',
    expatPopulation: 'Approximately 60,000 US citizens live in Japan',
    keyConsiderations: [
      'Japanese postal savings (Yucho) accounts are reportable',
      'iDeCo and NISA accounts must be reported on FBAR',
      'Japan does not use SWIFT/BIC for all domestic transfers — account details may differ from Western formats',
      'JPY/USD conversion rates can cause threshold surprises due to large yen denominations',
    ],
    overview: 'Japan has a significant US military and civilian expat population. Japanese bank accounts at megabanks, regional banks, and Japan Post Bank are reportable on FBAR. NISA investment accounts and iDeCo pension accounts are also reportable foreign financial accounts.',
    accountTypes: ['Futsuu yokin (ordinary savings)', 'Teiki yokin (fixed deposits)', 'NISA investment accounts', 'iDeCo pension accounts', 'Japan Post Bank savings', 'Securities accounts (shoken koza)'],
  },
  {
    slug: 'france',
    name: 'France',
    currency: 'Euro',
    currencyCode: 'EUR',
    commonBanks: ['BNP Paribas', 'Société Générale', 'Crédit Agricole', 'LCL', 'Crédit Mutuel'],
    pensionImplications: "French Assurance Vie (life insurance/investment products) are reportable on FBAR. PEA (Plan d'Épargne en Actions) and PEL (Plan d'Épargne Logement) accounts are also reportable. The US-France tax treaty (Article 18) provides pension relief for certain French social security benefits.",
    expatPopulation: 'Approximately 150,000 US citizens live in France',
    keyConsiderations: [
      'Assurance Vie contracts are reportable foreign financial accounts',
      'Livret A savings accounts are reportable despite their regulated nature',
      'PEA and PEL accounts must be reported on FBAR',
      'French investment funds (OPCVM) may be PFICs',
    ],
    overview: 'France is home to a large US expat community. French bank accounts, Livret A savings, Assurance Vie contracts, PEA investment accounts, and PEL housing savings plans are all reportable on FinCEN Form 114. Assurance Vie is particularly important as it is the most popular savings vehicle in France.',
    accountTypes: ['Compte courant (current accounts)', 'Livret A (regulated savings)', 'Assurance Vie (life insurance/investment)', 'PEA (equity savings plans)', 'PEL (housing savings plans)', 'Compte-titres (securities accounts)'],
  },
  {
    slug: 'switzerland',
    name: 'Switzerland',
    currency: 'Swiss Franc',
    currencyCode: 'CHF',
    commonBanks: ['UBS', 'Credit Suisse (now UBS)', 'PostFinance', 'Raiffeisen', 'Zürcher Kantonalbank'],
    pensionImplications: 'Swiss Pillar 2 (BVG/LPP occupational pension) and Pillar 3a (voluntary retirement savings) accounts are reportable on FBAR. The US-Switzerland tax treaty provides limited relief. Switzerland was at the center of the 2008-2014 FBAR enforcement wave.',
    expatPopulation: 'Approximately 30,000 US citizens live in Switzerland',
    keyConsiderations: [
      'Switzerland has been a primary FBAR enforcement target — IRS has pursued Swiss account holders aggressively',
      'Pillar 2 and 3a pension accounts are reportable',
      'Swiss bank secrecy no longer protects US persons — FATCA reporting is mandatory',
      'Vested benefits accounts (Freizügigkeitskonten) from past employment are reportable',
    ],
    overview: 'Switzerland has historical significance in FBAR enforcement. The US Department of Justice pursued thousands of US holders of undisclosed Swiss accounts from 2008-2014, resulting in billions in penalties. Today, all Swiss bank accounts, pension accounts (Pillar 2 and 3a), and investment accounts must be reported on FBAR.',
    accountTypes: ['Privatkonto (personal accounts)', 'Sparkonto (savings accounts)', 'Pillar 2 pension (BVG/LPP)', 'Pillar 3a retirement savings', 'Securities custody accounts', 'Vested benefits accounts'],
  },
  {
    slug: 'israel',
    name: 'Israel',
    currency: 'Israeli New Shekel',
    currencyCode: 'ILS',
    commonBanks: ['Bank Hapoalim', 'Bank Leumi', 'Discount Bank', 'Mizrahi Tefahot', 'Bank of Jerusalem'],
    pensionImplications: 'Israeli pension funds (Keren Pensia), provident funds (Kupat Gemel), and education funds (Keren Hishtalmut) are all reportable on FBAR. The US-Israel tax treaty provides some relief for certain pension distributions.',
    expatPopulation: 'Approximately 200,000 US citizens live in Israel',
    keyConsiderations: [
      'Keren Hishtalmut (education/training funds) are reportable even though commonly used as savings vehicles',
      'Kupat Gemel (provident funds) are reportable foreign financial accounts',
      'Israeli pension funds may be classified as PFICs',
      'Many US-Israel dual citizens are unaware of FBAR obligations',
    ],
    overview: 'Israel has a large population of US citizens and dual nationals. Israeli bank accounts, pension funds, provident funds, and the popular Keren Hishtalmut (education funds commonly used as savings vehicles) are all reportable on FinCEN Form 114. Many US-Israeli dual citizens are unaware of their FBAR filing obligations.',
    accountTypes: ['Cheshbon Over (checking accounts)', 'Cheshbon Chisachon (savings accounts)', 'Keren Pensia (pension funds)', 'Kupat Gemel (provident funds)', 'Keren Hishtalmut (education/training funds)', 'Tik Hashkaot (investment portfolios)'],
  },
  {
    slug: 'india',
    name: 'India',
    currency: 'Indian Rupee',
    currencyCode: 'INR',
    commonBanks: ['State Bank of India', 'HDFC Bank', 'ICICI Bank', 'Axis Bank', 'Kotak Mahindra'],
    pensionImplications: 'Indian PPF (Public Provident Fund) and EPF (Employees Provident Fund) accounts are reportable on FBAR. NRE (Non-Resident External) and NRO (Non-Resident Ordinary) accounts at Indian banks are also reportable. The US-India tax treaty does not specifically address these account types.',
    expatPopulation: 'Approximately 1 million US citizens of Indian origin maintain Indian accounts',
    keyConsiderations: [
      'NRE and NRO accounts are reportable foreign financial accounts',
      'PPF and EPF accounts are reportable even if contributions have stopped',
      'Fixed deposits (FDs) at Indian banks are reportable',
      'Indian mutual funds may be PFICs requiring Form 8621',
    ],
    overview: 'Many US citizens and green card holders of Indian origin maintain bank accounts and investments in India. NRE accounts, NRO accounts, PPF accounts, EPF accounts, and fixed deposits at Indian banks are all reportable on FBAR. The high INR/USD exchange rate means that INR balances exceeding roughly ₹8.5 lakh (at current rates) may trigger the $10,000 threshold.',
    accountTypes: ['NRE accounts (Non-Resident External)', 'NRO accounts (Non-Resident Ordinary)', 'PPF (Public Provident Fund)', 'EPF (Employees Provident Fund)', 'Fixed deposits (FDs)', 'Demat accounts (securities)'],
  },
];
