name = "wizard-config"
main = "src/index.ts"
compatibility_date = "2024-09-23"

[[kv_namespaces]]
binding = "WIZARD_CONFIG"
id = "0b57f354b13b45438eea43f44a2578ee"
preview_id = "1760fe2b2bb84a6aaa13b3ce0c608d20"
